{
  "hash": "15bf53e855aef04c12b3c7e0ffcecb4d",
  "result": {
    "engine": "knitr",
    "markdown": "# Forecasting with <tt>`fpp3`</tt>\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n## Introduction. {.unnumbered}\n\nForecasting is a structured way to reason about future values using observed data. In business and finance, forecasts support planning, inventory decisions, risk management, budgeting, and performance evaluation. This chapter uses one monthly sales series to connect the main pieces of a forecasting workflow: the data split, the mathematical notation, the model, the code, the forecast, and the out-of-sample error.\n\n## The forecast problem.\n\nThe empirical problem is to forecast one monthly time series: *Beer, Wine, and Distilled Alcoholic Beverages Sales*, following the original Matt Dancho example. The data comes from FRED, the Federal Reserve Economic Data database. The series belongs to the non-durable goods category and measures sales by U.S. merchant wholesalers, excluding manufacturers' sales branches and offices. The observations run from 2010-01-01 to 2022-10-31. The goal is to estimate models with information through December 2021 and evaluate their forecasts over the 10 available months of 2022.\n\nFor the full database details see: \nhttps://fred.stlouisfed.org/series/S4248SM144NCEN\n\nBefore starting, see: What is forecasting?\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nembed_url(\"https://youtu.be/zvd9oboayEc?si=DfK9JkSqapE8JHiw\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"vembedr\">\n<div>\n<iframe src=\"https://www.youtube.com/embed/zvd9oboayEc\" width=\"533\" height=\"300\" frameborder=\"0\" allowfullscreen=\"\" data-external=\"1\"></iframe>\n</div>\n</div>\n```\n\n:::\n:::\n\n\n\n\n## Mathematical notation for the chapter.\n\nBefore using R, it is useful to define the forecasting problem as a mathematical object. Let\n\n$$\ny_t = \\text{beer, wine, and distilled alcoholic beverages sales in month } t.\n$$\n\nThe observed series is\n\n$$\n\\{y_1, y_2, \\ldots, y_T\\},\n$$\n\nwhere the training sample ends in December 2021. The test sample contains the next ten observations, January 2022 through October 2022. The task is to produce ten forecasts:\n\n$$\n\\hat{y}_{T+h\\mid T}, \\qquad h = 1,2,\\ldots,10.\n$$\n\nThe notation $\\hat{y}_{T+h\\mid T}$ means: the forecast for month $T+h$ using only the information available up to month $T$. This point is essential. When we evaluate the forecast, the realized value $y_{T+h}$ is known to us after the fact. At the forecast origin, that future value was unavailable to the model.\n\nThe out-of-sample forecast error at horizon $h$ is\n\n$$\ne_{T+h} = y_{T+h} - \\hat{y}_{T+h\\mid T}.\n$$\n\nBecause this chapter compares several methods, we summarize the ten forecast errors with the mean absolute percentage error:\n\n$$\n\\text{MAPE}\n= \\frac{100}{10}\\sum_{h=1}^{10}\n\\left|\n\\frac{y_{T+h} - \\hat{y}_{T+h\\mid T}}{y_{T+h}}\n\\right|.\n$$\n\nThis formula has a simple interpretation. For each forecasted month, we compute the absolute error as a percentage of the observed value. Then we average those ten percentage errors. A MAPE of 5 means that, over the test period, the typical absolute error is about 5 percent of the realized monthly sales value.\n\nThe notation used throughout the chapter is:\n\n| Symbol | Meaning in this chapter |\n|---|---|\n| $t$ | Time index for monthly observations. |\n| $T$ | Last month in the training sample, December 2021. |\n| $h$ | Forecast horizon. Here $h=1,\\ldots,10$. |\n| $m$ | Seasonal period. For monthly data, $m=12$. |\n| $y_t$ | Observed sales in month $t$. |\n| $\\hat{y}_{T+h\\mid T}$ | Forecast for month $T+h$ using information through month $T$. |\n| $e_{T+h}$ | Forecast error in month $T+h$. |\n\nThis chapter therefore has a simple audit trail:\n\n| R object or function | Mathematical role |\n|---|---|\n| `beer_tbls` | The ordered time series $\\{y_t\\}$ with a monthly index. |\n| `beer_train` | The information set available at forecast origin $T$, written as $\\{y_1,\\ldots,y_T\\}$. |\n| `beer_2022` | The holdout sample $\\{y_{T+1},\\ldots,y_{T+10}\\}$ used only for evaluation. |\n| `model()` | Estimates the unknown parameters of a forecasting rule from `beer_train`. |\n| `forecast(h = 10)` | Computes $\\hat{y}_{T+h\\mid T}$ for $h=1,\\ldots,10$. |\n| `accuracy(..., beer_2022)` | Compares $\\hat{y}_{T+h\\mid T}$ with $y_{T+h}$ and calculates error measures such as MAPE. |\n\nThis notation is the bridge between the formulas, the code, and the reported results.\n\n## The data.\n\nFirst load the R packages.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load libraries\nlibrary(fpp3)\nlibrary(timetk)     # Toolkit for working with time series in R.\nlibrary(tidyquant)  # Loads tidyverse, financial pkgs, used to get data.\nlibrary(dplyr)      # Database manipulation.\nlibrary(ggplot2)    # Plots.\nlibrary(tibble)     # Tables.\nlibrary(kableExtra) # Tables.\nlibrary(knitr)      \nlibrary(bit64)      # Useful in the machine learning workflow.\nlibrary(sweep)      # Broom-style tidiers for the forecast package.\nlibrary(forecast)   # Forecasting models and predictions package.\nlibrary(seasonal)\nlibrary(tictoc)\n```\n:::\n\n\n\n\nWe can conveniently download the data directly from the FRED API in one line of code.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Beer, Wine, Distilled Alcoholic Beverages, in Millions USD.\nbeer <- tq_get(\"S4248SM144NCEN\", get = \"economic.data\", \n               from = \"2010-01-01\", to = \"2022-10-31\")\n\nif (!is.data.frame(beer) || !all(c(\"date\", \"price\") %in% names(beer))) {\n  fred_beer <- read.csv(\n    \"https://fred.stlouisfed.org/graph/fredgraph.csv?id=S4248SM144NCEN\",\n    stringsAsFactors = FALSE\n  )\n\n  beer <- fred_beer %>%\n    transmute(\n      date = as.Date(observation_date),\n      price = as.numeric(S4248SM144NCEN)\n    ) %>%\n    filter(date >= as.Date(\"2010-01-01\"), date <= as.Date(\"2022-10-31\")) %>%\n    filter(!is.na(price))\n}\n\nif (!is.data.frame(beer) || !all(c(\"date\", \"price\") %in% names(beer))) {\n  stop(\"The FRED beer sales series could not be loaded as a data frame.\")\n}\n```\n:::\n\n\n\n\nThe first rows show the structure of the data set. By default the value column is named *price*, although these are sales figures in monetary terms. According to the main FRED reference, these are in millions of dollars and are reported before seasonal adjustment.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(beer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  symbol         date       price\n  <chr>          <date>     <int>\n1 S4248SM144NCEN 2010-01-01  6558\n2 S4248SM144NCEN 2010-02-01  7481\n3 S4248SM144NCEN 2010-03-01  9475\n4 S4248SM144NCEN 2010-04-01  9424\n5 S4248SM144NCEN 2010-05-01  9351\n6 S4248SM144NCEN 2010-06-01 10552\n```\n\n\n:::\n:::\n\n\n\n\nWe rename the value column so that the code matches the economic meaning of the variable.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer <- beer %>%\n  rename(sales = price)\n\ntail(beer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 3\n  symbol         date       sales\n  <chr>          <date>     <int>\n1 S4248SM144NCEN 2022-05-01 16714\n2 S4248SM144NCEN 2022-06-01 17899\n3 S4248SM144NCEN 2022-07-01 15193\n4 S4248SM144NCEN 2022-08-01 17069\n5 S4248SM144NCEN 2022-09-01 16443\n6 S4248SM144NCEN 2022-10-01 15585\n```\n\n\n:::\n:::\n\n\n\nThe column name now identifies the variable as sales.\n\nVisualization is particularly important for time series analysis and forecasting. The first plot identifies the point where the data are split into training and test samples. The *training* data set is the sample used to estimate the model. The *test* data set is the holdout sample used to evaluate the final forecasts. In this chapter, the test set is used after the forecasts have already been produced.\n\nIt is also important to see the time series because normally the models will perform better if we can identify basic characteristics such as trend and seasonality. This data set clearly has a trend and a seasonality as people drink more alcohol in December. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer %>%\n  ggplot(aes(date, sales)) +\n  # Train Region:\n  annotate(\"text\", x = ymd(\"2013-01-01\"), y = 14000, \n           color = \"black\", label = \"Train region\") +\n  geom_rect(xmin = as.numeric(ymd(\"2022-01-01\")), \n            xmax = as.numeric(ymd(\"2022-09-30\")), ymin = 0, ymax = 20000, \n            alpha = 0.02, fill = \"pink\") +\n  annotate(\"text\", x = ymd(\"2022-06-01\"), y = 9000,\n           color = \"black\", label = \"Test\\nregion\") +\n  # Data.\n  geom_line(col = \"black\") +\n  geom_point(col = \"black\", alpha = 0.5, size = 2) +\n  # Aesthetics.\n  theme_tq() +\n  scale_x_date(date_breaks = \"1 year\", date_labels = \"%Y\") +\n  labs(subtitle = \n  \"Train (2010 - 2021), and test set (Jan 2022 to Oct 2022)\",\n  x = \"Date\", y = \"Sales\",\n       caption = \"The test region is hidden from the models during fitting;\n       it is shown here to evaluate the 10-month ahead forecast.\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![Beer, Wine, and Distilled Alcoholic Beverages Sales.](01-forecasting-with-fpp3_files/figure-html/fig-bwadabs-1.png){#fig-bwadabs width=672}\n:::\n:::\n\n\n\n\nThe forecasting task is to predict the 10 months in the test region, from January to October 2022.\n\nHere is a zoom version of the plot above.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer %>%\n  filter(date > as.Date(\"2020-01-01\")) %>%\n  ggplot(aes(date, sales)) +\n  annotate(\"text\", x = ymd(\"2020-08-01\"), y = 17000, \n           color = \"black\", label = \"Train region\") +\n  geom_rect(xmin = as.numeric(ymd(\"2022-01-01\")), \n            xmax = as.numeric(ymd(\"2022-09-30\")), ymin = 0, ymax = 20000, \n            alpha = 0.02, fill = \"pink\") +\n  annotate(\"text\", x = ymd(\"2022-05-01\"), y = 14000,\n           color = \"black\", label = \"Test region\") +\n  geom_line(col = \"black\") +\n  geom_point(col = \"black\", alpha = 0.5, size = 5) +\n  theme_tq() +\n  scale_x_date(date_breaks = \"1 year\", date_labels = \"%Y\") +\n  labs(subtitle = \n  \"Train (2010 - 2021) and test set (Jan 2022 to Oct 2022)\",\n  x = \"Date\", y = \"Sales\",\n       caption = \"The test region is hidden from the models during fitting;\n       it is shown here to evaluate the 10-month ahead forecast.\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![Zoom: Beer, Wine, and Distilled Alcoholic Beverages Sales.](01-forecasting-with-fpp3_files/figure-html/fig-zbwadabs-1.png){#fig-zbwadabs width=672}\n:::\n:::\n\n\n\n\n## Time series properties.\n\nThe forecasting techniques should capture the main time-series components, especially trend and seasonality. Here we use the @hyndman2021forecasting <tt>`fpp3`</tt> package to study those properties before estimating the forecasting models. To use <tt>`fpp3`</tt>, we transform <tt>`beer`</tt> from a <tt>`tibble`</tt> to a <tt>`tsibble`</tt> object.\n\nA time series is an ordered process, so the position of each observation is part of the information. For many business series, the observed value can be understood as the combination of three latent components:\n\n$$\ny_t = T_t + S_t + R_t\n$$\n\nin an additive decomposition, or\n\n$$\ny_t = T_t \\times S_t \\times R_t\n$$\n\nin a multiplicative decomposition. Here, $T_t$ is the trend-cycle component, $S_t$ is the seasonal component, and $R_t$ is the remaining irregular component. The multiplicative version is natural when seasonal movements grow or shrink with the level of the series. In business sales, December seasonality may be larger in dollar terms when the whole series is at a higher level.\n\nThe decomposition works as a diagnostic step before forecasting. It tells us what kind of structure a forecast model must explain: long-run movement, repeated monthly seasonality, and unusual shocks.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_tbls <- beer\nbeer_tbls$date <- yearmonth(beer_tbls$date)\nbeer_tbls <- as_tsibble(beer_tbls)\n```\n:::\n\n\n\n\nAccording to @hyndman2021forecasting, the X-11 method was originated in the US Census Bureau and further developed by Statistics Canada. The decomposition process tends to be highly robust to outliers and level shifts in the time series. The details of the X-11 method are described in @dagum2016seasonal.\n\nThe code below asks X-11 to estimate the unobserved components $T_t$, $S_t$, and $R_t$ from the observed series $y_t$. The word *estimate* is important: we observe sales directly. The trend and irregular component are inferred from the observed series using moving averages and seasonal filters.\n\nThe decomposition can be read as follows:\n\n| Element | Role |\n|---|---|\n| Input | The observed monthly sales series $y_t$. |\n| Estimated trend-cycle | The slowly moving component $T_t$. |\n| Estimated seasonality | The recurring monthly pattern $S_t$. |\n| Estimated irregular component | The remaining short-run movement $R_t$. |\n| Use in this chapter | Diagnose what later forecast models need to capture. |\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_tbls %>%\n  model(x11 = X_13ARIMA_SEATS(sales ~ x11())) %>%\n  components() %>%\n  autoplot() +\n  labs(y = \"Sales\", x = \"Date\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![A multiplicative decomposition of beer sales using X-11.](01-forecasting-with-fpp3_files/figure-html/fig-amdobsux-1.png){#fig-amdobsux width=672}\n:::\n:::\n\n\n\nThe trend shows a clear change in the first half of 2020. The next table inspects that period directly.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_tbls %>%\n  model(x11 = X_13ARIMA_SEATS(sales ~ x11())) %>%\n  components() %>%\n  select(date, sales, trend) %>%\n  filter_index(\"2020-03\" ~ \"2020-10\") %>%\n  head(8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tsibble: 8 x 3 [1M]\n       date sales  trend\n      <mth> <dbl>  <dbl>\n1 2020 mar. 13281 13618.\n2 2020 abr. 12225 13724.\n3 2020 may. 13977 13828.\n4 2020 jun. 16065 13914.\n5 2020 jul. 15577 15298.\n6 2020 ago. 15225 15329.\n7 2020 sep. 15446 15338.\n8 2020 oct. 16024 15324.\n```\n\n\n:::\n:::\n\n\n\nThe consumption trend significantly increased from June 2020 to July 2020. It is big enough to create a discontinuity in the trend plot below.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_tbls %>%\n  model(x11 = X_13ARIMA_SEATS(sales ~ x11())) %>%\n  components() %>%\n  select(date, trend) %>%\n  ggplot(aes(yearmonth(date), trend)) + \n  geom_point(alpha = 0.3, size = 4) +\n  geom_point(aes(x = yearmonth(\"2020 jun.\"), y = 13950.99), \n             alpha = 0.3, size = 4, colour = \"red\") +\n  geom_point(aes(x = yearmonth(\"2020 jul.\"), y = 15356.13), \n             alpha = 0.3, size = 4, colour = \"red\") +\n  labs(y = \"Trend\", x = \"Date\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![Trend discontinuity.](01-forecasting-with-fpp3_files/figure-html/fig-td-1.png){#fig-td width=672}\n:::\n:::\n\n\n\n\nThere are also three negative spikes in the irregular component.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_tbls %>%\n  model(x11 = X_13ARIMA_SEATS(sales ~ x11())) %>%\n  components() %>%\n  select(date, sales, irregular) %>%\n  filter(irregular < 0.95) %>%\n  head(3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tsibble: 3 x 3 [1M]\n       date sales irregular\n      <mth> <dbl>     <dbl>\n1 2020 abr. 12225     0.892\n2 2020 dic. 16353     0.868\n3 2021 dic. 18201     0.912\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_tbls %>%\n  model(x11 = X_13ARIMA_SEATS(sales ~ x11())) %>%\n  components() %>%\n  select(date, irregular) %>%\n  ggplot(aes(yearmonth(date), irregular)) + \n  geom_point(alpha = 0.3, size = 4) +\n  geom_point(aes(x = yearmonth(\"2020 apr.\"), y = 0.8894670), \n             alpha = 0.3, size = 4, colour = \"red\") +\n  geom_point(aes(x = yearmonth(\"2020 dec.\"), y = 0.8688517), \n             alpha = 0.3, size = 4, colour = \"red\") +\n  geom_point(aes(x = yearmonth(\"2021 dec.\"), y = 0.9099203), \n             alpha = 0.3, size = 4, colour = \"red\") +\n  labs(y = \"Irregular\", x = \"Date\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![Three negative spikes in the irregular component.](01-forecasting-with-fpp3_files/figure-html/fig-tnsitic-1.png){#fig-tnsitic width=672}\n:::\n:::\n\n\n\n\nThe trend and irregular events are consistent across decomposition techniques. We implement the SEATS decomposition below. SEATS stands for *Seasonal Extraction in ARIMA Time Series*. According to @hyndman2021forecasting, this procedure was developed at the Bank of Spain, and is now widely used by government agencies around the world. See @dagum2016seasonal for further details.\n\nSEATS reaches the same conceptual destination as X-11 through an ARIMA-based route. It starts from an ARIMA representation of the series and decomposes that model into trend-cycle, seasonal, and irregular pieces. In practical terms, this is a useful robustness check. If X-11 and SEATS point to the same relevant events, the conclusion is less likely to be an artifact of one specific decomposition algorithm.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_tbls %>%\n  model(seats = X_13ARIMA_SEATS(sales ~ seats())) %>%\n  components() %>%\n  autoplot() +\n  labs(y = \"Sales\", x = \"Date\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![A decomposition of beer sales obtained using SEATS.](01-forecasting-with-fpp3_files/figure-html/fig-adobsous-1.png){#fig-adobsous width=672}\n:::\n:::\n\n\n\n\nA seasonal plot is similar to a time plot except that the data are plotted against the individual *seasons*, in this case months, in which the data were observed. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_tbls %>%\n  gg_season(sales, labels = \"both\") +\n  labs(y = \"Sales\", x = \"Date\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![Seasonal plot: Beer sales.](01-forecasting-with-fpp3_files/figure-html/fig-spbs-1.png){#fig-spbs width=672}\n:::\n:::\n\n\n\nAnd this is the zoom version of the plot above.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_tbls %>%\n  filter_index(\"2019-01\" ~ .) %>%\n  gg_season(sales, labels = \"both\", size = 2) +\n  geom_point() +\n  labs(y = \"Sales\", x = \"Date\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![Zoom. Seasonal plot: Beer sales.](01-forecasting-with-fpp3_files/figure-html/fig-zspbs-1.png){#fig-zspbs width=672}\n:::\n:::\n\n\n\n\nAn alternative plot that emphasises the seasonal patterns is where the data for each month are collected together in separate mini time plots.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_tbls %>%\n  gg_subseries(sales) +\n  labs(y = \"Sales\", x = \"Date\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![Seasonal subseries plot of monthly beer sales.](01-forecasting-with-fpp3_files/figure-html/fig-sspombs-1.png){#fig-sspombs width=672}\n:::\n:::\n\n\n\nDecember is the month of the year with the highest average sales, followed by June. January is the month of the year with the lowest average sales, followed by February.\n\nFollowing @hyndman2021forecasting, just as correlation measures the extent of a linear relationship between two variables, autocorrelation measures the linear relationship between lagged values of a time series. When data have a trend, the autocorrelations for small lags tend to be large and positive because observations nearby in time are also nearby in value. So the ACF of a trended time series tends to have positive values that slowly decrease as the lags increase. When data are seasonal, the autocorrelations will be larger for the seasonal lags (at multiples of the seasonal period, in this case 12) than for other lags.\n\nFor lag $k$, the autocorrelation is the correlation between the series and its own lagged version:\n\n$$\n\\rho_k = \\operatorname{Corr}(y_t, y_{t-k}).\n$$\n\nThe ACF plot estimates $\\rho_k$ for several values of $k$. If $\\rho_{12}$, $\\rho_{24}$, and $\\rho_{36}$ are relatively large, the plot is telling us that observations twelve, twenty-four, and thirty-six months apart tend to move together. That is the mathematical signature of annual seasonality in monthly data.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_tbls %>%\n  ACF(sales, lag_max = 60) %>%\n  autoplot()\n```\n\n::: {.cell-output-display}\n![ACF of monthly beer sales.](01-forecasting-with-fpp3_files/figure-html/fig-aombs-1.png){#fig-aombs width=672}\n:::\n:::\n\n\n\nBeer sales is both trended and seasonal. The slow decrease in the ACF as the lags increase is due to the trend, while the *scalloped* shape is due to the seasonality.\n\n## Forecasts with <tt>`fpp3`</tt>.\n\nHere we implement some selected forecast techniques using the @hyndman2021forecasting <tt>`fpp3`</tt> package. First define the training and test set (2022).\n\nAll forecasting methods in this section follow the same logic:\n\n$$\n\\text{training data}\n\\longrightarrow\n\\text{estimated model}\n\\longrightarrow\n\\text{ten forecasts}\n\\longrightarrow\n\\text{out-of-sample error}.\n$$\n\nIn R, this becomes `beer_train %>% model(...) %>% forecast(h = 10)`, followed by `accuracy(..., beer_2022)`. The syntax is compact, and each step has a clear statistical meaning. The model is fitted using only observations up to December 2021. The forecast is then compared against the ten months in 2022.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_train <- beer_tbls %>%\n  select(date, sales) %>%\n  filter_index(. ~ \"2021-12\")\n\nbeer_2022 <- beer_tbls %>%\n  select(date, sales) %>%\n  filter_index(\"2022-01\" ~ .)\n```\n:::\n\n\n\n\n## Four simple techniques.\n\nWe estimate four simple forecast techniques. The *mean* method sets every forecast equal to the historical average. The *naïve* method repeats the last observed value. The *seasonal naïve* method repeats the last observed value from the same season. The *drift* method allows the forecasts to increase or decrease along a straight-line trend.\n\nThese simple methods are useful because their equations are transparent. Let $m=12$ be the seasonal period for monthly data.\n\nMean method:\n\n$$\n\\hat{y}_{T+h\\mid T} = \\bar{y}\n= \\frac{1}{T}\\sum_{t=1}^{T} y_t.\n$$\n\nNaïve method:\n\n$$\n\\hat{y}_{T+h\\mid T} = y_T.\n$$\n\nSeasonal naïve method:\n\n$$\n\\hat{y}_{T+h\\mid T} = y_{T+h-m},\n\\qquad h=1,\\ldots,m.\n$$\n\nFor this chapter, $h=1,\\ldots,10$, so every forecast is copied from the same month in the previous year. The January 2022 forecast is the January 2021 value, the February 2022 forecast is the February 2021 value, and so on.\n\nDrift method:\n\n$$\n\\hat{y}_{T+h\\mid T}\n= y_T + h\\left(\\frac{y_T-y_1}{T-1}\\right).\n$$\n\nThe drift method is a naïve extension that adds a straight-line slope estimated from the first and last observations in the training sample.\n\nThe four formulas can be compared directly:\n\n| Method | Forecast rule | Main idea |\n|---|---|---|\n| Mean | $\\hat{y}_{T+h\\mid T}=\\bar{y}$ | Use the historical average for every future month. |\n| Naïve | $\\hat{y}_{T+h\\mid T}=y_T$ | Repeat the last observed value. |\n| Seasonal naïve | $\\hat{y}_{T+h\\mid T}=y_{T+h-m}$ | Copy the same month from the previous year. |\n| Drift | $\\hat{y}_{T+h\\mid T}=y_T+h(y_T-y_1)/(T-1)$ | Extend a straight-line historical slope. |\n \nThis table is useful pedagogically because the code below estimates four named models, while the equations show exactly what each model does.\n\nEstimate the four models.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_fit <- beer_train %>%\n  model(\"fpp3: mean\" = MEAN(sales), \"fpp3: naïve\" = NAIVE(sales),\n    \"fpp3: seasonal naïve\" = SNAIVE(sales), \n    \"fpp3: drift\" = RW(sales ~ drift()))\nglance(beer_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  .model                 sigma2\n  <chr>                   <dbl>\n1 fpp3: mean           5430658.\n2 fpp3: naïve          3279288.\n3 fpp3: seasonal naïve  491364.\n4 fpp3: drift          3279288.\n```\n\n\n:::\n:::\n\n\n\n\nThe 10-month forecasts.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_fc <- beer_fit %>%\n  fabletools::forecast(h = \"10 months\")\n```\n:::\n\n\n\n\nWe compute the MAPE for each forecast rule.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmape_table <- fabletools::accuracy(beer_fc, beer_2022) %>%\n  select(.model, MAPE) %>%\n  arrange(desc(-MAPE))\nmape_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  .model                MAPE\n  <chr>                <dbl>\n1 fpp3: seasonal naïve  3.89\n2 fpp3: naïve          18.1 \n3 fpp3: drift          20.9 \n4 fpp3: mean           23.5 \n```\n\n\n:::\n:::\n\n\n\n\nThe object `beer_fc` contains the ten values $\\hat{y}_{T+h\\mid T}$ for each model. The object `beer_2022` contains the ten realized values $y_{T+h}$. Therefore, `accuracy(beer_fc, beer_2022)` performs evaluation only: it compares already-produced forecasts against the holdout sample.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsn_mape <- fabletools::accuracy(beer_fc, beer_2022) %>%\n  filter(.model == \"fpp3: seasonal naïve\") %>%\n  select(MAPE) %>%\n  unlist()\nsn_mape\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    MAPE \n3.889793 \n```\n\n\n:::\n:::\n\n\n\n\nThe forecast results can be inspected visually.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_fc %>%\n  autoplot(beer_tbls, level = NULL) +\n  geom_vline(xintercept = as.Date(\"2022-01-01\"), lty = 2) +\n  labs(y = \"Sales\", x = \"Date\") +\n  guides(colour = guide_legend(title = \"Forecast:\")) +\n  theme(legend.position = \"bottom\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![fpp3: four simple forecasts.](01-forecasting-with-fpp3_files/figure-html/fig-ffsf-1.png){#fig-ffsf width=672}\n:::\n:::\n\n\n\nThe full-range plot compresses the 2022 comparison. The zoom version focuses on the evaluation window.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_zoom <- beer_tbls %>%\n  select(date, sales) %>%\n  filter_index(\"2019-12\" ~ .)\n\nbeer_fc %>%\n  autoplot(beer_zoom, level = NULL, lwd = 2)  +\n  geom_vline(xintercept = as.Date(\"2022-01-01\"), lty = 2) +\n  labs(y = \"Sales\", x = \"Date\") +\n  guides(colour = guide_legend(title = \"Forecast:\")) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Zoom. fpp3: four simple forecasts.](01-forecasting-with-fpp3_files/figure-html/fig-zffsf-1.png){#fig-zffsf width=672}\n:::\n:::\n\n\n\nThe seasonal naïve forecasts can be inspected separately.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_zoom <- beer_tbls %>%\n  select(date, sales) %>%\n  filter_index(\"2019-12\" ~ .)\n\nbeer_sn_fc <- beer_fc %>%\n  filter(.model == \"fpp3: seasonal naïve\") \n\n  ggplot(beer_zoom, aes(yearmonth(date), sales), lwd = 2, alpha = 0.4) +\n  geom_line() +\n  geom_point(size = 5, color = \"black\", alpha = 0.5, \n             shape = 21, fill = \"black\") +\n  geom_point(aes(y = .mean), size = 5, \n             color = \"red\", alpha = 0.5, shape = 21, \n             fill = \"red\", data = beer_sn_fc) +\n  geom_line(aes(y = .mean), color = \"red\", size = 0.5, data = beer_sn_fc) +\n    geom_vline(xintercept = as.numeric(as.Date(\"2021-12-01\")), \n               linetype = 2) +\n  labs(y = \"Sales\", x = \"Date\",\n       caption = c(paste(\"MAPE=\",(round(sn_mape, 5))))) +\n  theme(legend.position = \"bottom\") +\n    scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![Zoom. fpp3: seasonal naïve forecasts.](01-forecasting-with-fpp3_files/figure-html/fig-zfsnf-1.png){#fig-zfsnf width=672}\n:::\n:::\n\n\n\nSimple techniques can be strong baselines. A more complex model earns its place only when it improves on these transparent rules.\n\n## Exponential smoothing.\n\nAccording to @hyndman2021forecasting, forecasts produced using exponential smoothing methods are weighted averages of past observations, with the weights decaying exponentially as the observations get older. In other words, the more recent the observation the higher the associated weight. This framework generates reliable forecasts quickly and for a wide range of time series, which is a great advantage and of major importance to applications in industry.\n\nThe simplest exponential smoothing idea can be written as\n\n$$\n\\ell_t = \\alpha y_t + (1-\\alpha)\\ell_{t-1},\n\\qquad 0 < \\alpha < 1.\n$$\n\nHere, $\\ell_t$ is the current estimate of the level of the series. A large $\\alpha$ gives more weight to the newest observation; a small $\\alpha$ makes the estimated level move more slowly. ETS extends this idea by estimating a level component, a trend component, a seasonal component, and an error structure.\n\nIn this subsection, we let the <tt>`ETS()`</tt> function select the model by minimising the AICc.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_ets <- beer_train %>%\n  model(ETS(sales))\nreport(beer_ets)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: sales \nModel: ETS(M,A,M) \n  Smoothing parameters:\n    alpha = 0.1602027 \n    beta  = 0.00961933 \n    gamma = 0.0001010184 \n\n  Initial states:\n    l[0]     b[0]     s[0]    s[-1]    s[-2]    s[-3]    s[-4]     s[-5]\n 9247.67 37.19533 1.168876 1.031489 1.036782 0.993476 1.051993 0.9885615\n    s[-6]    s[-7]     s[-8]     s[-9]    s[-10]    s[-11]\n 1.125236 1.062294 0.9661073 0.9855889 0.8314213 0.7581742\n\n  sigma^2:  0.0021\n\n     AIC     AICc      BIC \n2536.576 2541.433 2587.063 \n```\n\n\n:::\n:::\n\n\n\n\nThe <tt>`ETS(M,A,M)`</tt> corresponds to a Holt-Winters multiplicative method with multiplicative errors for when seasonal variations are changing proportional to the level of the series. The notation `ETS(M,A,M)` means:\n\n| Letter | Meaning in this model |\n|---|---|\n| First `M` | Multiplicative error: forecast uncertainty is proportional to the level. |\n| `A` | Additive trend: the trend adds or subtracts a roughly constant amount. |\n| Second `M` | Multiplicative seasonality: seasonal effects scale with the level. |\n\nA compact way to read the selected model is\n\n$$\ny_t =\n(\\ell_{t-1}+b_{t-1})s_{t-m}(1+\\varepsilon_t),\n$$\n\nwhere $\\ell_t$ is level, $b_t$ is trend, $s_t$ is seasonality, $m=12$, and $\\varepsilon_t$ is a one-step-ahead innovation. The corresponding point forecast is approximately\n\n$$\n\\hat{y}_{T+h\\mid T}\n=\n(\\ell_T + h b_T)s_{T+h-m},\n\\qquad h=1,\\ldots,12.\n$$\n\nThe model is transparent once we name its estimated parts: `ETS()` estimates the level, trend, seasonal states, and smoothing parameters; `forecast()` advances those states into the ten future months.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncomponents(beer_ets) %>%\n  autoplot() +\n  labs(x = \"Date\", y = \"Sales\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![fpp3: ETS components.](01-forecasting-with-fpp3_files/figure-html/fig-fec-1.png){#fig-fec width=672}\n:::\n:::\n\n\n\n\nThe ETS(M,A,M) 10-month forecast.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_ets_fc <- beer_ets %>%\n  fabletools::forecast(h = 10)\nbeer_ets_fc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A fable: 10 x 4 [1M]\n# Key:     .model [1]\n   .model          date\n   <chr>          <mth>\n 1 ETS(sales) 2022 ene.\n 2 ETS(sales) 2022 feb.\n 3 ETS(sales) 2022 mar.\n 4 ETS(sales) 2022 abr.\n 5 ETS(sales) 2022 may.\n 6 ETS(sales) 2022 jun.\n 7 ETS(sales) 2022 jul.\n 8 ETS(sales) 2022 ago.\n 9 ETS(sales) 2022 sep.\n10 ETS(sales) 2022 oct.\n# ℹ 2 more variables: sales <dist>, .mean <dbl>\n```\n\n\n:::\n:::\n\n\n\n\nThe ETS(M,A,M) MAPE.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nets_mape <- fabletools::accuracy(beer_ets_fc, beer_2022) %>%\n  select(MAPE) %>%\n  unlist()\nets_mape\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  MAPE \n3.7717 \n```\n\n\n:::\n:::\n\n\n\nThe <tt>`ETS(M,A,M)`</tt> forecast can be plotted against the observed series.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_ets %>%\n  fabletools::forecast(h = 10) %>%\n  autoplot(beer_tbls) +\n  geom_vline(xintercept = as.Date(\"2022-01-01\"), lty = 2) +\n  labs(x = \"Date\", y = \"Sales\") +\n  theme(legend.position = \"bottom\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![fpp3: ETS(M,A,M) forecast.](01-forecasting-with-fpp3_files/figure-html/fig-fef-1.png){#fig-fef width=672}\n:::\n:::\n\n\n\nThe full-range plot compresses the forecast comparison, so the zoom view is easier to read.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  ggplot(beer_zoom, aes(yearmonth(date), sales), lwd = 2, alpha = 0.4) +\n  geom_line() +\n  geom_point(size = 5, color = \"black\", alpha = 0.5, \n             shape = 21, fill = \"black\") +\n  geom_point(aes(y = .mean), size = 5, \n             color = \"red\", alpha = 0.5, shape = 21, \n             fill = \"red\", data = beer_ets_fc) +\n  geom_line(aes(y = .mean), color = \"red\", size = 0.5, data = beer_ets_fc) +\n  geom_vline(xintercept = as.numeric(as.Date(\"2021-12-01\")), \n               linetype = 2) +\n  labs(x = \"Date\", y = \"Sales\",\n       caption = c(paste(\"MAPE=\",(round(ets_mape, 5))))) +\n  theme(legend.position = \"bottom\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![Zoom. fpp3: ETS(M,A,M) forecast.](01-forecasting-with-fpp3_files/figure-html/fig-zfef-1.png){#fig-zfef width=672}\n:::\n:::\n\n\n\nThe MAPE table is extended with the ETS result.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmape_updated <- mape_table %>%\n  add_row(.model = \"fpp3: ETS(M,A,M)\", MAPE = ets_mape) %>%\n  arrange(desc(-MAPE))\nmape_updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n  .model                MAPE\n  <chr>                <dbl>\n1 fpp3: ETS(M,A,M)      3.77\n2 fpp3: seasonal naïve  3.89\n3 fpp3: naïve          18.1 \n4 fpp3: drift          20.9 \n5 fpp3: mean           23.5 \n```\n\n\n:::\n:::\n\n\n\n\n## ARIMA.\n\nAccording to @hyndman2021forecasting, exponential smoothing models emphasize trend and seasonality. ARIMA models emphasize autocorrelation: the way a series is related to its own recent values and recent forecast errors. The <tt>`ARIMA()`</tt> function combines unit root tests, AICc minimisation, and maximum likelihood estimation to select an ARIMA model. Setting <tt>`stepwise = FALSE`</tt> and <tt>`approximation = FALSE`</tt> asks R to run a more exhaustive search.\n\nFollowing the notation used in Chapter 9 of @hyndman2021forecasting, a non-seasonal ARIMA model is written as\n\n$$\n\\text{ARIMA}(p,d,q).\n$$\n\nThe three orders have direct meanings:\n\n| Order | Name | What it controls |\n|---|---|\n| $p$ | Autoregressive order | How many lagged values of the transformed series enter the model. |\n| $d$ | Differencing order | How many times the series is differenced to remove persistent trend. |\n| $q$ | Moving-average order | How many lagged forecast errors enter the model. |\n\nThe basic building blocks can be read without compact operator notation. An autoregressive model of order $p$ uses recent values:\n\n$$\ny_t\n=\nc+\\phi_1y_{t-1}+\\phi_2y_{t-2}+\\cdots+\\phi_py_{t-p}+\\varepsilon_t.\n$$\n\nThe coefficient $\\phi_1$ measures how much the previous observation helps explain the current observation after accounting for the other terms. A moving-average model of order $q$ uses recent forecast errors:\n\n$$\ny_t\n=\nc+\\varepsilon_t+\\theta_1\\varepsilon_{t-1}\n\\theta_2\\varepsilon_{t-2}+\\cdots+\\theta_q\\varepsilon_{t-q}.\n$$\n\nThe coefficient $\\theta_1$ measures how much yesterday's unexpected shock carries into today's value. Differencing is the step that turns levels into changes:\n\n$$\ny'_t = y_t-y_{t-1}.\n$$\n\nFor monthly data, seasonal ARIMA adds seasonal orders:\n\n$$\n\\text{ARIMA}(p,d,q)(P,D,Q)_{m},\n$$\n\nwhere $m=12$ for monthly seasonality. The seasonal orders have parallel meanings:\n\n| Order | Name | What it controls in monthly data |\n|---|---|---|\n| $P$ | Seasonal autoregressive order | Dependence on values one or more years apart. |\n| $D$ | Seasonal differencing order | Differences against the same month in a previous year. |\n| $Q$ | Seasonal moving-average order | Dependence on seasonal forecast errors. |\n| $m$ | Seasonal period | The number of observations in one seasonal cycle. Here $m=12$. |\n\nIn words, ARIMA first chooses the amount of ordinary differencing $d$ and seasonal differencing $D$. Then it chooses how many lagged values and lagged errors are useful: $p$, $q$, $P$, and $Q$. The `ARIMA()` function performs an organized model search: it tries candidate orders, estimates parameters by maximum likelihood, and chooses a specification using AICc.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_arima <- beer_train %>%\n  model(arima_auto = ARIMA(sales, stepwise = FALSE, approx = FALSE))\nreport(beer_arima)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: sales \nModel: ARIMA(4,1,1)(0,1,1)[12] \n\nCoefficients:\n          ar1      ar2     ar3      ar4      ma1     sma1\n      -0.0716  -0.0164  0.2239  -0.3366  -0.7664  -0.6620\ns.e.   0.1064   0.1049  0.0962   0.0842   0.0830   0.1049\n\nsigma^2 estimated as 311616:  log likelihood=-1015.88\nAIC=2045.75   AICc=2046.66   BIC=2065.88\n```\n\n\n:::\n:::\n\n\n\n\nThe selected model is reported by R. In this chapter, the selected specification is ARIMA(4,1,1)(0,1,1)[12]. This can be read piece by piece:\n\n| Part | Meaning in this fitted model |\n|---|---|\n| $p=4$ | Use four recent lagged values after differencing. |\n| $d=1$ | Use one ordinary difference to reduce trend. |\n| $q=1$ | Use one recent forecast error. |\n| $P=0$ | No seasonal autoregressive term is selected. |\n| $D=1$ | Use one seasonal difference, comparing a month with the same month one year earlier. |\n| $Q=1$ | Use one seasonal forecast error. |\n| $m=12$ | Monthly data have a twelve-month seasonal cycle. |\n\nThe model therefore says: first remove ordinary trend and annual seasonal persistence; then model what remains using four recent values, one recent error, and one seasonal error. That reading is the main pedagogical point. The order notation tells us what information the model uses.\n\nThe residuals for the best ARIMA model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_arima %>%\n  select(arima_auto) %>%\n  gg_tsresiduals()\n```\n\n::: {.cell-output-display}\n![Residuals from the fitted fpp3 ARIMA(4,1,1)(0,1,1)[12] model.](01-forecasting-with-fpp3_files/figure-html/fig-rftffam-1.png){#fig-rftffam width=672}\n:::\n:::\n\n\n\n\nThe residual diagnostic is the model audit. For a well-specified ARIMA model, the residuals should behave approximately like white noise:\n\n$$\nE(\\hat{\\varepsilon}_t) \\approx 0,\n\\qquad\n\\operatorname{Corr}(\\hat{\\varepsilon}_t,\\hat{\\varepsilon}_{t-k}) \\approx 0\n\\quad \\text{for } k>0.\n$$\n\nIf the residual ACF still shows strong structure, the model has left predictable information unused. If the residuals look mostly uncorrelated, the model has captured the main time dependence available in the training data.\n\nThe forecast for the best ARIMA model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_arima_fc <- beer_arima %>%\n  fabletools::forecast(h = \"10 months\")\nbeer_arima_fc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A fable: 10 x 4 [1M]\n# Key:     .model [1]\n   .model          date\n   <chr>          <mth>\n 1 arima_auto 2022 ene.\n 2 arima_auto 2022 feb.\n 3 arima_auto 2022 mar.\n 4 arima_auto 2022 abr.\n 5 arima_auto 2022 may.\n 6 arima_auto 2022 jun.\n 7 arima_auto 2022 jul.\n 8 arima_auto 2022 ago.\n 9 arima_auto 2022 sep.\n10 arima_auto 2022 oct.\n# ℹ 2 more variables: sales <dist>, .mean <dbl>\n```\n\n\n:::\n:::\n\n\n\n\nThe ARIMA MAPE.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\narima_mape <- fabletools::accuracy(beer_arima_fc, beer_2022) %>%\n  select(MAPE) %>%\n  unlist()\narima_mape\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    MAPE \n4.401266 \n```\n\n\n:::\n:::\n\n\n\n\nThe ARIMA forecast results can be inspected visually.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_arima_fc %>%\n  autoplot(beer_tbls, level = NULL) +\n  geom_vline(xintercept = as.Date(\"2022-01-01\"), lty = 2) +\n  labs(y = \"Sales\", x = \"Date\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![fpp3: ARIMA(4,1,1)(0,1,1)[12] forecast.](01-forecasting-with-fpp3_files/figure-html/fig-faf-1.png){#fig-faf width=672}\n:::\n:::\n\n\n\n\nThe full-range plot compresses the 2022 comparison. The zoom version focuses on the forecast months.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  ggplot(beer_zoom, aes(yearmonth(date), sales), lwd = 2, alpha = 0.4) +\n  geom_line() +\n  geom_point(size = 5, color = \"black\", alpha = 0.5, \n             shape = 21, fill = \"black\") +\n  geom_point(aes(y = .mean), size = 5, \n             color = \"red\", alpha = 0.5, shape = 21, \n             fill = \"red\", data = beer_arima_fc) +\n  geom_line(aes(y = .mean), color = \"red\", size = 0.5, data = beer_arima_fc) +\n  geom_vline(xintercept = as.numeric(as.Date(\"2021-12-01\")), \n               linetype = 2) +\n  labs(x = \"Date\", y = \"Sales\",\n       caption = c(paste(\"MAPE=\",(round(arima_mape, 5))))) +\n  theme(legend.position = \"bottom\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![Zoom. fpp3: ARIMA(4,1,1)(0,1,1)[12] forecast.](01-forecasting-with-fpp3_files/figure-html/fig-zfaf-1.png){#fig-zfaf width=672}\n:::\n:::\n\n\n\n\nThe MAPE table is extended with the ARIMA result.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmape_updated <- mape_updated %>%\n  add_row(.model = \"fpp3: ARIMA(4,1,1)(0,1,1)[12]\", MAPE = arima_mape) %>%\n  arrange(desc(-MAPE))\nmape_updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 2\n  .model                         MAPE\n  <chr>                         <dbl>\n1 fpp3: ETS(M,A,M)               3.77\n2 fpp3: seasonal naïve           3.89\n3 fpp3: ARIMA(4,1,1)(0,1,1)[12]  4.40\n4 fpp3: naïve                   18.1 \n5 fpp3: drift                   20.9 \n6 fpp3: mean                    23.5 \n```\n\n\n:::\n:::\n\n\n\n\nThe ARIMA result should be interpreted together with the seasonal naïve and ETS results. The test window has only ten months, so small MAPE differences deserve caution. In this render, ETS has a MAPE around 3.77, seasonal naïve around 3.89, and ARIMA around 4.40. That ranking suggests that trend and seasonality explain most of the test period, and that the extra ARIMA autocorrelation structure improves the simple baselines while ETS remains the strongest model in this particular holdout window.\n\n## Neural network.\n\nNeural networks are flexible nonlinear forecasting models. With time series data, lagged values of the series can be used as inputs, just as lagged values appear in a linear autoregression. When a neural network uses autoregressive inputs, we call it a neural network autoregression or NNAR model.\n\nThe starting point is still the same forecasting question: can recent history help predict the next value? A linear autoregression answers that question with a weighted sum of lagged observations. A NNAR model allows the weights to interact through hidden units, so the effect of one lag can depend on the values of other lags.\n\n$$\ny_t = f(y_{t-1}, y_{t-2}, \\ldots, y_{t-p}, y_{t-m}, y_{t-2m}, \\ldots) + \\varepsilon_t.\n$$\n\nHere, $f(\\cdot)$ is the forecasting rule learned from the training data. The inputs are lagged sales values. For example, $y_{t-1}$ is last month's sales and $y_{t-12}$ is sales in the same month one year earlier.\n\nWith one hidden layer, a neural network forecast can be described in three stages. First, the model forms an input vector $x_t$ from lagged sales values. Second, each hidden unit combines those inputs and passes the result through a nonlinear function. Third, the output layer combines the hidden units into the forecast:\n\n$$\nf(x_t)\n=\nw_0 + \\sum_{j=1}^{k} w_j \\sigma(a_j + v_j^\\top x_t),\n$$\n\nwhere $x_t$ is the vector of lagged inputs, $k$ is the number of hidden units, $\\sigma(\\cdot)$ is the nonlinear activation function, and the weights $w_j$, $a_j$, and $v_j$ are estimated from the training data.\n\nThe equation can be read as a recipe:\n\n| Component | Plain-language role |\n|---|---|\n| $x_t$ | The lagged sales values available before the forecast is made. |\n| $v_j^\\top x_t$ | A weighted summary of those lagged values for hidden unit $j$. |\n| $\\sigma(\\cdot)$ | A nonlinear transformation that allows curved relationships. |\n| $w_j$ | The weight assigned to hidden unit $j$ in the final forecast. |\n| $k$ | The number of hidden units, which controls flexibility. |\n\nThe audit question for NNAR is therefore simple: what information enters the model? In this chapter, the NNAR model receives lagged sales values only. Future test values, external regressors and hand-adjusted forecasts stay outside the model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_nnet <- beer_train %>%\n  model(NNETAR(sales))\nreport(beer_nnet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: sales \nModel: NNAR(15,1,8)[12] \n\nAverage of 20 networks, each of which is\na 15-8-1 network with 137 weights\noptions were - linear output units \n\nsigma^2 estimated as 1138\n```\n\n\n:::\n:::\n\n\n\n\nThe reported model is NNAR(15,1,8)[12]. This notation can be read as follows:\n\n| Part | Meaning |\n|---|---|\n| 15 | The model uses recent non-seasonal lag information up to 15 months. |\n| 1 | The model also includes one seasonal lag structure for monthly data. |\n| 8 | The hidden layer has 8 units. |\n| [12] | The seasonal cycle has 12 months. |\n\nIn plain language, `NNETAR()` learns a nonlinear forecasting rule from recent monthly history and annual seasonal history.\n\nThe calculation can be read in four steps:\n\n| Step | Interpretation |\n|---|---|\n| Build inputs | Collect recent lags and seasonal lags of sales. |\n| Hidden layer | Combine those lags into $k=8$ nonlinear summaries. |\n| Output layer | Combine the nonlinear summaries into one forecast. |\n| Evaluation | Compare the ten forecasted values with the ten 2022 observations. |\n\nThe forecast for the best NNAR model.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_nnet_fc <- beer_nnet %>%\n  fabletools::forecast(h = \"10 months\")\nbeer_nnet_fc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A fable: 10 x 4 [1M]\n# Key:     .model [1]\n   .model             date        sales  .mean\n   <chr>             <mth>       <dist>  <dbl>\n 1 NNETAR(sales) 2022 ene. sample[5000] 13103.\n 2 NNETAR(sales) 2022 feb. sample[5000] 14773.\n 3 NNETAR(sales) 2022 mar. sample[5000] 16721.\n 4 NNETAR(sales) 2022 abr. sample[5000] 15705.\n 5 NNETAR(sales) 2022 may. sample[5000] 17027.\n 6 NNETAR(sales) 2022 jun. sample[5000] 19154.\n 7 NNETAR(sales) 2022 jul. sample[5000] 16794.\n 8 NNETAR(sales) 2022 ago. sample[5000] 17780.\n 9 NNETAR(sales) 2022 sep. sample[5000] 17238.\n10 NNETAR(sales) 2022 oct. sample[5000] 16788.\n```\n\n\n:::\n:::\n\n\n\n\nThe NNAR MAPE.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnnet_mape <- fabletools::accuracy(beer_nnet_fc, beer_2022) %>%\n  select(MAPE) %>%\n  unlist()\nnnet_mape\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    MAPE \n6.020197 \n```\n\n\n:::\n:::\n\n\n\nThe NNAR forecast results can be inspected visually.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbeer_nnet_fc %>%\n  autoplot(beer_tbls, level = NULL) +\n  geom_vline(xintercept = as.Date(\"2022-01-01\"), lty = 2) +\n  labs(y = \"Sales\", x = \"Date\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![fpp3: NNAR(15,1,8)[12] forecast.](01-forecasting-with-fpp3_files/figure-html/fig-fnf-1.png){#fig-fnf width=672}\n:::\n:::\n\n\n\n\nThe full-range plot compresses the 2022 comparison. The zoom version focuses on the forecast months.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  ggplot(beer_zoom, aes(yearmonth(date), sales), lwd = 2, alpha = 0.4) +\n  geom_line() +\n  geom_point(size = 5, color = \"black\", alpha = 0.5, \n             shape = 21, fill = \"black\") +\n  geom_point(aes(y = .mean), size = 5, \n             color = \"red\", alpha = 0.5, shape = 21, \n             fill = \"red\", data = beer_nnet_fc) +\n  geom_line(aes(y = .mean), color = \"red\", size = 0.5, data = beer_nnet_fc) +\n  geom_vline(xintercept = as.numeric(as.Date(\"2021-12-01\")), \n               linetype = 2) +\n  labs(x = \"Date\", y = \"Sales\",\n       caption = c(paste(\"MAPE=\",(round(nnet_mape, 5))))) +\n  theme(legend.position = \"bottom\") +\n  scale_y_continuous(labels = scales::dollar)\n```\n\n::: {.cell-output-display}\n![Zoom. fpp3: NNAR(15,1,8)[12] forecast.](01-forecasting-with-fpp3_files/figure-html/fig-zfnf-1.png){#fig-zfnf width=672}\n:::\n:::\n\n\n\n\nThe MAPE table is extended with the NNAR result.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmape_updated <- mape_updated %>%\n  add_row(.model = \"fpp3: NNAR(15,1,8)[12]\", MAPE = nnet_mape) %>%\n  arrange(desc(-MAPE))\nmape_updated\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 2\n  .model                         MAPE\n  <chr>                         <dbl>\n1 fpp3: ETS(M,A,M)               3.77\n2 fpp3: seasonal naïve           3.89\n3 fpp3: ARIMA(4,1,1)(0,1,1)[12]  4.40\n4 fpp3: NNAR(15,1,8)[12]         6.02\n5 fpp3: naïve                   18.1 \n6 fpp3: drift                   20.9 \n7 fpp3: mean                    23.5 \n```\n\n\n:::\n:::\n\n\n\n\nThe NNAR result is informative even though it ranks below ETS, seasonal naïve and ARIMA in this holdout period. Its MAPE is around 8.79. This tells us that the added nonlinear flexibility produced weaker 2022 forecasts for this short test window. A useful teaching point follows: a flexible model can learn complicated patterns, yet forecasting performance still depends on whether those patterns persist into the holdout period.\n\nThe final table is an empirical comparison over one specific holdout window. The mathematical object being compared is always the same:\n\n$$\n\\left\\{\n\\hat{y}_{T+1\\mid T},\n\\hat{y}_{T+2\\mid T},\n\\ldots,\n\\hat{y}_{T+10\\mid T}\n\\right\\}.\n$$\n\nWhat changes from row to row is the rule used to generate those ten forecasts. The seasonal naïve method copies the previous year's monthly pattern; ETS updates level, trend, and seasonality through smoothing equations; ARIMA models autocorrelation after differencing; NNAR learns a nonlinear function of lagged observations. The MAPE table is therefore the last step in a complete chain: model assumption, estimated parameters, forecast values, forecast errors, and summary accuracy.\n\nThe main empirical interpretation is that the strong seasonal structure of the series is central. Seasonal naïve already performs well, which means that copying last year's monthly pattern is a serious benchmark. ETS improves slightly by updating level, trend and seasonality. ARIMA also performs well, suggesting that differencing and autocorrelation help, although the selected ARIMA model is a little less accurate than ETS here. NNAR is more flexible, yet its holdout error is larger in this example. For students, the lesson is direct: out-of-sample error is the criterion that disciplines model complexity.\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n",
    "supporting": [
      "01-forecasting-with-fpp3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/vembedr-0.1.5/css/vembedr.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}